% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Parima Ahmadipour, Omid Sani, Maryam Shanechi
%   Shanechi Lab, University of Southern California, 2020
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function sourceDependentSettings = getSubjectSpecificPreprocessingSettings(fileName)

if contains(fileName, 'CP1')
    sourceDependentSettings = [
        struct('label', 'rightacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 66  69], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 70  73], 'type', 'IIR', 'order', 4); ...
        ]);
        struct('label', 'rightofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 66  69], 'type', 'IIR', 'order', 4); ...
        ]);
    ];
elseif contains(fileName, 'CP2')
    sourceDependentSettings = [
        struct('label', 'rightacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 50  53], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 83  86], 'type', 'IIR', 'order', 4); ...
        ]);
        struct('label', 'rightofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 6.3  8.3], 'type', 'IIR', 'order', 4); ...
        ]);
        struct('label', 'leftacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 47  50], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 67  70], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 86  89], 'type', 'IIR', 'order', 4); ...
        ]);

    ];

elseif contains(fileName, 'CP3')

    sourceDependentSettings = [
        struct('label', 'rightacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 43  47], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 66  71], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 80  83], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 88  91], 'type', 'IIR', 'order', 4); ...
        ]);
        struct('label', 'rightofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 45  48], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 68  71], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 80  83], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 88  93], 'type', 'IIR', 'order', 4); ...

        ]);
        struct('label', 'leftacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 47  51], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 66  70], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 78  82], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 89  92], 'type', 'IIR', 'order', 4); ...


        ]);
        struct('label', 'leftofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 23  26], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 42  45], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 47  50], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 73  76], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 79  82], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 89  94], 'type', 'IIR', 'order', 4); ...

        ]);
    ];

elseif contains(fileName, 'CP4')
    sourceDependentSettings = [
        struct('label', 'rightacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 44  47], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 49  52], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 66  69], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 80  85], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 89  93], 'type', 'IIR', 'order', 4); ...
        ]);
        struct('label', 'rightofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 21  24], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 44  46], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 48  51], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 66  69], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 81  93], 'type', 'IIR', 'order', 4); ...

        ]);
        struct('label', 'leftacc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 43  46], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 50  53], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 66  69], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 80  85], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 89  93], 'type', 'IIR', 'order', 4); ...

        ]);
        struct('label', 'leftofc', 'DFilterSpecs', [
             struct('shape', 'BS', 'Fc', [ 63  70], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 80  84], 'type', 'IIR', 'order', 4); ...
             struct('shape', 'BS', 'Fc', [ 90  95], 'type', 'IIR', 'order', 4); ...


        ]);
    ];

end

end

